name: Deploy Workflow

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    name: portfolioDeploy
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      REACT_APP_FORM_ACTION_URL: ${{ secrets.REACT_APP_FORM_ACTION_URL }}
      REACT_APP_INVOLVEMENT_API_BASE_URL: ${{ secrets.REACT_APP_INVOLVEMENT_API_BASE_URL }}
      REACT_APP_INVOLVEMENT_API_APP_ID: ${{ secrets.REACT_APP_INVOLVEMENT_API_APP_ID }}
